---
- name: Get automation secret
  become_user: root
  become_method: sudo
  shell: |
      python3 -c 'g={"multisite_users": {}}; \
      exec(open("/omd/sites/{{cmk_site}}/etc/check_mk/multisite.d/wato/users.mk").read(), g); \
      print(g["multisite_users"]["automation"]["automation_secret"])'
  register: python_output

- name: Extract secret
  set_fact:
      automation_secret: "{{ python_output.stdout }}"

- name: Install Checkmk agent
  apt:
      deb: /omd/sites/{{cmk_site}}/share/check_mk/agents/check-mk-agent_{{cmk_version}}-1_all.deb
      state: present

- name: Add localhost to monitoring
  script: files/perform_rest_action.py --api-entrypoint {{ api_entrypoint }} --automation-secret {{ automation_secret }} --action add_localhost
  args:
      executable: python3

- name: Activate changes
  script: files/perform_rest_action.py --api-entrypoint {{ api_entrypoint }} --automation-secret {{ automation_secret }} --action activate_changes
  args:
    executable: python3

- name: Register controller to {{cmk_site}} site
  become: yes
  become_user: root
  become_method: sudo
  shell: |
      cmk-agent-ctl register --trust-cert -s localhost -i {{cmk_site}} -H localhost -U automation -P {{ automation_secret }}

- name: Discover services
  script: files/perform_rest_action.py --api-entrypoint {{ api_entrypoint }} --automation-secret {{ automation_secret }} --action discover_services
  args:
      executable: python3

- name: Activate changes
  script: files/perform_rest_action.py --api-entrypoint {{ api_entrypoint }} --automation-secret {{ automation_secret }} --action activate_changes
  args:
      executable: python3
